--- #YAML:1.0
name: AutoCurry
version: 0.1001
author: ~
abstract: |-
  automatically create currying variants of functions
license: perl
requires:
  Carp: 0
  Test::More: 0
provides:
  AutoCurry:
    file: lib/AutoCurry.pm
    version: 0.1001
generated_by: Module::Build version 0.2608
